"""
Full metasurface beam steering simulation.

Loads the phase library from unit_cell_sweep.py, computes the required
phase gradient for the target steering angle, assigns pillar widths,
and runs a 2D FDTD simulation of the full supercell.

Usage
-----
    python run.py 01_beam_steering/full_array_sim.py [options]

    or edit the USER PARAMETERS block below and run directly.

Requires
--------
    results/phase_library.npz  (generated by unit_cell_sweep.py)

Output
------
    results/pillar_layout.png          geometry visualisation
    results/epsilon_map.png            MEEP permittivity map
    results/farfield_<angle>deg.png    angular spectrum
    results/farfield_<angle>deg.npz    raw farfield data
    stdout: summary table with steering efficiency
"""

import argparse
import os
import sys

import numpy as np

# ── path setup ────────────────────────────────────────────────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _ROOT)

from utils.device    import print_platform_info
from utils.materials import load_material
from utils.viz       import (plot_angular_spectrum, plot_epsilon,
                              plot_pillar_layout)


# ══════════════════════════════════════════════════════════════════════════════
#  USER PARAMETERS  ← edit these before running
#  All can also be set via CLI flags (see --help)
# ══════════════════════════════════════════════════════════════════════════════

WAVELENGTH  = 0.532   # μm  — free-space wavelength (UV-vis: 0.40 – 0.70 μm)
ANGLE       = 30.0    # °   — target beam steering angle from normal
MS_WIDTH    = 5.0     # μm  — metasurface lateral width
                      #       (more width = more supercells = sharper farfield)
PILLAR_H    = 0.60    # μm  — pillar height (must match unit_cell_sweep)
N_GLASS     = 1.5     #     — substrate refractive index
RESOLUTION  = 32      #     — MEEP pixels/μm (32=fast preview, 64=accurate)
LIB_DIR     = "results"   # relative to this script — where phase_library.npz is
OUT_DIR     = "results"   # relative to this script — where to write outputs

# ══════════════════════════════════════════════════════════════════════════════


# ─────────────────────────────────────────────────────────────────────────────
# CLI  (mirrors the USER PARAMETERS block above)
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Full metasurface beam-steering simulation.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--wavelength",  type=float, default=WAVELENGTH,
                   help="Free-space wavelength in μm")
    p.add_argument("--angle",       type=float, default=ANGLE,
                   help="Target steering angle in degrees")
    p.add_argument("--ms-width",    type=float, default=MS_WIDTH,
                   dest="ms_width", help="Metasurface lateral width in μm")
    p.add_argument("--pillar-h",    type=float, default=PILLAR_H,
                   dest="pillar_h", help="Pillar height in μm")
    p.add_argument("--n-glass",     type=float, default=N_GLASS,
                   dest="n_glass",  help="Substrate refractive index")
    p.add_argument("--resolution",  type=int,   default=RESOLUTION,
                   help="MEEP pixels per μm")
    p.add_argument("--lib-dir",     default=LIB_DIR, dest="lib_dir",
                   help="Directory containing phase_library.npz")
    p.add_argument("--outdir",      default=OUT_DIR,
                   help="Output directory")
    return p.parse_args()


# ─────────────────────────────────────────────────────────────────────────────
# Phase library helpers
# ─────────────────────────────────────────────────────────────────────────────

def load_phase_library(lib_dir, script_dir):
    """Load phase_library.npz; exit with helpful message if missing."""
    path = os.path.join(script_dir, lib_dir, "phase_library.npz")
    if not os.path.exists(path):
        sys.exit(
            f"\n[error] Phase library not found: {path}\n"
            "        Run unit_cell_sweep.py first:\n"
            "          python run.py 01_beam_steering/unit_cell_sweep.py\n"
        )
    data = np.load(path, allow_pickle=True)
    print(f"[library] Loaded: {path}")
    return data


def assign_pillar_widths(lib, target_phases):
    """
    Map target phases → pillar widths via nearest-neighbour lookup.

    Strategy
    --------
    Both target and library phases are normalised to [0, 2π) before
    comparison to avoid ±π ambiguity in np.angle output.

    Parameters
    ----------
    lib           : npz archive from unit_cell_sweep
    target_phases : array of required phases in radians (any range)

    Returns
    -------
    widths : array of pillar widths in μm
    errors : array of |target_phase - assigned_phase| in degrees
    """
    w_lib  = lib["widths"]
    ph_lib = lib["phases"]                       # wrapped [-π, π]

    # Normalise library phases to [0, 2π)
    ph_lib_norm = ph_lib % (2 * np.pi)

    assigned = np.zeros(len(target_phases))
    errors   = np.zeros(len(target_phases))

    for i, phi in enumerate(target_phases):
        phi_norm = phi % (2 * np.pi)
        # Circular distance on [0, 2π)
        diff = np.abs(ph_lib_norm - phi_norm)
        diff = np.minimum(diff, 2 * np.pi - diff)   # wrap-around distance
        idx = int(np.argmin(diff))
        assigned[i] = w_lib[idx]
        errors[i]   = np.degrees(diff[idx])

    return assigned, errors


# ─────────────────────────────────────────────────────────────────────────────
# Geometry builder
# ─────────────────────────────────────────────────────────────────────────────

def build_geometry(x_positions, pillar_widths, pillar_height,
                   period, pillar_medium, n_glass,
                   sy, y_subs_top):
    """
    Return a list of mp.GeometricObject for the full metasurface supercell.

    The glass substrate fills from cell bottom to y_subs_top.
    Pillars sit on the substrate at their assigned x positions.
    """
    import meep as mp

    glass = mp.Medium(index=n_glass)
    sx    = x_positions[-1] - x_positions[0] + period   # full cell width

    geom = [
        # Glass substrate
        mp.Block(
            size=mp.Vector3(mp.inf, y_subs_top + sy / 2, mp.inf),
            center=mp.Vector3(0, -(sy / 2 - (y_subs_top + sy / 2) / 2)),
            material=glass,
        )
    ]

    y_pillar_ctr = y_subs_top + pillar_height / 2

    for x0, w in zip(x_positions, pillar_widths):
        if w > 0.02 * period:          # skip negligibly thin pillars
            geom.append(
                mp.Block(
                    size=mp.Vector3(w, pillar_height, mp.inf),
                    center=mp.Vector3(x0, y_pillar_ctr),
                    material=pillar_medium,
                )
            )

    return geom


# ─────────────────────────────────────────────────────────────────────────────
# Angular spectrum via FFT
# ─────────────────────────────────────────────────────────────────────────────

def angular_spectrum(ez_dft, sx, wavelength, pad_factor=8):
    """
    Compute farfield angular spectrum from DFT near-field by FFT.

    For a periodic simulation with Bloch k=0 (normal incidence), the
    DFT Ez field across x gives the amplitude of each diffraction order
    directly via FFT.

    Parameters
    ----------
    ez_dft     : 1D complex array  — Ez DFT along x at monitor
    sx         : float             — physical width of the array in μm
    wavelength : float             — free-space wavelength in μm
    pad_factor : int               — zero-padding factor for angle resolution

    Returns
    -------
    theta_deg : array  angles in degrees (sorted, propagating only)
    intensity : array  |E_z|² at each angle
    """
    Nx = len(ez_dft)
    dx = sx / Nx                       # spatial sampling in μm

    # Zero-padded FFT for finer angular resolution
    Ez_fft = np.fft.fftshift(np.fft.fft(ez_dft, n=Nx * pad_factor))
    kx     = np.fft.fftshift(
                 np.fft.fftfreq(Nx * pad_factor, d=dx)
             )                         # spatial frequency in cycles/μm

    kx_rad = 2 * np.pi * kx           # rad/μm
    k0_rad = 2 * np.pi / wavelength   # rad/μm

    sin_theta = kx_rad / k0_rad
    propagating = np.abs(sin_theta) <= 1.0

    theta_deg = np.degrees(np.arcsin(sin_theta[propagating]))
    intensity  = np.abs(Ez_fft[propagating]) ** 2

    # Sort by angle
    order = np.argsort(theta_deg)
    return theta_deg[order], intensity[order]


# ─────────────────────────────────────────────────────────────────────────────
# MEEP simulation
# ─────────────────────────────────────────────────────────────────────────────

def run_sim(args, lib, outdir):
    import meep as mp

    wavelength  = args.wavelength
    angle_deg   = args.angle
    ms_width    = args.ms_width
    pillar_h    = args.pillar_h
    n_glass     = args.n_glass
    resolution  = args.resolution

    freq   = 1.0 / wavelength
    period = float(lib["period"])

    # ── supercell design ──────────────────────────────────────────────────────
    # Generalised Snell: sin(θ) = λ / Λ  →  Λ = λ / sin(θ)
    supercell_period = wavelength / np.sin(np.radians(angle_deg))
    n_per_super      = max(2, int(np.round(supercell_period / period)))
    actual_period    = n_per_super * period
    actual_angle     = np.degrees(np.arcsin(wavelength / actual_period))

    # Number of supercells that fit in ms_width
    n_supers = max(1, int(np.round(ms_width / actual_period)))
    n_cells  = n_per_super * n_supers
    sx       = n_cells * period

    print(f"\n[sim] ── Supercell design ──────────────────────────")
    print(f"[sim]   Target angle       : {angle_deg:.1f}°")
    print(f"[sim]   Required period Λ  : {supercell_period*1000:.1f} nm")
    print(f"[sim]   Unit cells / super : {n_per_super}")
    print(f"[sim]   Actual Λ           : {actual_period*1000:.1f} nm")
    print(f"[sim]   Actual angle       : {actual_angle:.2f}°")
    print(f"[sim]   Supercells in sim  : {n_supers}")
    print(f"[sim]   Total unit cells   : {n_cells}")
    print(f"[sim]   Simulation width   : {sx:.2f} μm")

    # ── phase profile ─────────────────────────────────────────────────────────
    # x positions: centred at 0
    x_positions   = (np.arange(n_cells) - (n_cells - 1) / 2.0) * period
    # Linear phase gradient: φ(x) = k₀ sin(θ_actual) x
    target_phases = (2 * np.pi / wavelength) * np.sin(np.radians(actual_angle)) * x_positions

    pillar_widths, phase_errors = assign_pillar_widths(lib, target_phases)

    print(f"\n[sim] ── Pillar assignment ─────────────────────────")
    print(f"[sim]   Width range : {pillar_widths.min()*1000:.1f} – "
                                  f"{pillar_widths.max()*1000:.1f} nm")
    print(f"[sim]   Phase error : mean {phase_errors.mean():.1f}°  "
                                 f"max {phase_errors.max():.1f}°")

    # ── load pillar material ──────────────────────────────────────────────────
    mat_name     = str(lib["material"])
    pillar_mat   = load_material(mat_name)
    pillar_medium = pillar_mat(wavelength)

    # ── cell layout ───────────────────────────────────────────────────────────
    dpml        = wavelength
    subs_thick  = 1.5 * wavelength
    air_thick   = 2.0 * wavelength
    sy          = dpml + subs_thick + pillar_h + air_thick + dpml

    y_bot       = -sy / 2
    y_subs_top  = y_bot + dpml + subs_thick      # interface substrate/pillar
    y_src       = y_bot + dpml + 0.4 * wavelength
    y_mon       = y_subs_top + pillar_h + 0.4 * wavelength

    # ── build MEEP objects ────────────────────────────────────────────────────
    geometry = build_geometry(
        x_positions, pillar_widths, pillar_h,
        period, pillar_medium, n_glass,
        sy, y_subs_top,
    )

    sources = [
        mp.Source(
            mp.GaussianSource(frequency=freq, fwidth=0.05 * freq),
            component=mp.Ez,
            center=mp.Vector3(0, y_src),
            size=mp.Vector3(sx, 0),
        )
    ]

    sim = mp.Simulation(
        cell_size=mp.Vector3(sx, sy),
        boundary_layers=[mp.PML(dpml)],
        geometry=geometry,
        sources=sources,
        k_point=mp.Vector3(),      # Bloch BC, normal incidence
        resolution=resolution,
        eps_averaging=True,
    )

    dft_mon = sim.add_dft_fields(
        [mp.Ez], freq, freq, 1,
        center=mp.Vector3(0, y_mon),
        size=mp.Vector3(sx, 0),
    )

    decay_pt = mp.Vector3(sx / 4, y_mon)

    print(f"\n[sim] ── Running MEEP (resolution={resolution}) ────")

    # Save geometry plot before running
    if mp.am_master():
        plot_epsilon(
            sim, filename=os.path.join(outdir, "epsilon_map.png"),
            title=f"Permittivity map  |  λ={wavelength*1000:.0f}nm  "
                  f"|  angle={actual_angle:.1f}°"
        )

    sim.run(
        until_after_sources=mp.stop_when_fields_decayed(
            20, mp.Ez, decay_pt, 1e-7
        )
    )

    # ── extract farfield ──────────────────────────────────────────────────────
    ez_dft = sim.get_dft_array(dft_mon, mp.Ez, 0)
    theta_deg, intensity = angular_spectrum(ez_dft, sx, wavelength)

    return (theta_deg, intensity, actual_angle,
            x_positions, pillar_widths, target_phases)


# ─────────────────────────────────────────────────────────────────────────────
# Efficiency summary
# ─────────────────────────────────────────────────────────────────────────────

def print_efficiency(theta_deg, intensity, actual_angle):
    """Print a simple steering efficiency summary to stdout."""
    import meep as mp
    if not mp.am_master():
        return

    norm     = intensity / intensity.max()
    total    = intensity.sum()
    window   = 5.0                         # ±5° around steering peak

    in_peak  = intensity[np.abs(theta_deg - actual_angle) <= window]
    in_zero  = intensity[np.abs(theta_deg) <= window]

    eff_steer = in_peak.sum() / total * 100 if total > 0 else 0
    eff_zero  = in_zero.sum() / total * 100 if total > 0 else 0

    peak_angle = theta_deg[np.argmax(intensity)]

    print(f"\n[result] ── Efficiency summary ─────────────────────")
    print(f"[result]   Peak at          : {peak_angle:.1f}°")
    print(f"[result]   Target angle     : {actual_angle:.1f}°")
    print(f"[result]   Steering eff     : {eff_steer:.1f}%  (power in ±{window}° of target)")
    print(f"[result]   Zeroth-order eff : {eff_zero:.1f}%  (residual forward beam)")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main():
    args   = parse_args()
    outdir = os.path.join(_HERE, args.outdir)
    os.makedirs(outdir, exist_ok=True)

    print_platform_info()

    lib = load_phase_library(args.lib_dir, _HERE)

    (theta_deg, intensity, actual_angle,
     x_positions, pillar_widths, target_phases) = run_sim(args, lib, outdir)

    import meep as mp
    if mp.am_master():
        # ── pillar layout ─────────────────────────────────────────────────────
        plot_pillar_layout(
            x_positions, pillar_widths,
            pillar_height=args.pillar_h,
            period=float(lib["period"]),
            target_phases=target_phases,
            filename=os.path.join(outdir, "pillar_layout.png"),
        )

        # ── farfield ──────────────────────────────────────────────────────────
        tag = f"{args.angle:.0f}deg"
        plot_angular_spectrum(
            theta_deg, intensity,
            target_angle=args.angle,
            actual_angle=actual_angle,
            wavelength=args.wavelength,
            filename=os.path.join(outdir, f"farfield_{tag}.png"),
        )

        # ── save raw data ─────────────────────────────────────────────────────
        np.savez(
            os.path.join(outdir, f"farfield_{tag}.npz"),
            theta_deg    = theta_deg,
            intensity    = intensity,
            actual_angle = actual_angle,
            target_angle = args.angle,
            wavelength   = args.wavelength,
        )
        print(f"[sim] Raw data saved → {outdir}/farfield_{tag}.npz")

        print_efficiency(theta_deg, intensity, actual_angle)

    print("\n[done] All outputs in:", outdir)


if __name__ == "__main__":
    main()
