"""
Solver comparison: MEEP FDTD vs torcwa RCWA.

Loads a MEEP phase library and an RCWA phase library, prints a side-by-side
metadata table, optionally prints a speed comparison, and generates a two-panel
overlay plot of |T| and ∠T vs pillar width.

Prerequisite
------------
Run the RCWA sweep first to generate the RCWA library:
    python run.py 05_solver_comparison/rcwa_sim.py

A MEEP phase library must also exist (generated by 01_beam_steering):
    python run.py 01_beam_steering/unit_cell_sweep.py

Usage
-----
    # Basic comparison (no timing)
    python run.py 05_solver_comparison/compare_solvers.py

    # With MEEP sweep time for speed table
    python run.py 05_solver_comparison/compare_solvers.py --meep-time 1820

    # Custom library paths
    python run.py 05_solver_comparison/compare_solvers.py \\
        --meep-lib path/to/phase_library.npz \\
        --rcwa-lib path/to/rcwa_phase_library.npz

    # Shift RCWA phase curve so first point matches MEEP (removes global offset)
    python run.py 05_solver_comparison/compare_solvers.py --align-phase

Options
-------
    --meep-lib     01_beam_steering/results/phase_library.npz
    --rcwa-lib     05_solver_comparison/results/rcwa_phase_library.npz
    --meep-time    optional: MEEP sweep wall time in seconds (for speed table)
    --align-phase  shift RCWA phase so first point matches MEEP (default: off)
    --outdir       results  output directory
    --no-plot      skip comparison plot

Output
------
    results/solver_comparison.png   two-panel |T| and ∠T overlay
"""

import argparse
import os
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _ROOT)

from utils.device import print_platform_info
from utils.sweep  import PhaseLibrary
from utils.viz    import plot_solver_comparison


# ══════════════════════════════════════════════════════════════════════════════
#  DEFAULTS
# ══════════════════════════════════════════════════════════════════════════════

_MEEP_LIB_DEFAULT = os.path.join(
    _ROOT, "01_beam_steering", "results", "phase_library.npz"
)
_RCWA_LIB_DEFAULT = os.path.join(
    _HERE, "results", "rcwa_phase_library.npz"
)
OUT_DIR = "results"


# ══════════════════════════════════════════════════════════════════════════════
#  CLI
# ══════════════════════════════════════════════════════════════════════════════

def parse_args():
    p = argparse.ArgumentParser(
        description="Compare MEEP FDTD and torcwa RCWA phase libraries.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--meep-lib",    default=_MEEP_LIB_DEFAULT,
                   dest="meep_lib", help="Path to MEEP phase_library.npz")
    p.add_argument("--rcwa-lib",    default=_RCWA_LIB_DEFAULT,
                   dest="rcwa_lib", help="Path to RCWA rcwa_phase_library.npz")
    p.add_argument("--meep-time",   type=float, default=None,
                   dest="meep_time",
                   help="MEEP sweep wall time in seconds (for speed table)")
    p.add_argument("--align-phase", action="store_true", dest="align_phase",
                   help="Shift RCWA phase curve so first point matches MEEP")
    p.add_argument("--outdir",      default=OUT_DIR)
    p.add_argument("--no-plot",     action="store_true", dest="no_plot")
    return p.parse_args()


# ══════════════════════════════════════════════════════════════════════════════
#  HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def _load_rcwa_time(rcwa_path):
    """Return sweep_time_s from rcwa .npz, or None if key absent."""
    try:
        data = np.load(rcwa_path, allow_pickle=True)
        return float(data["sweep_time_s"])
    except (KeyError, Exception):
        return None


def print_metadata_table(lib_meep, lib_rcwa, rcwa_time_s):
    """Print side-by-side library metadata."""
    rows = [
        ("material",       lib_meep.material,          lib_rcwa.material),
        ("wavelength (nm)",f"{lib_meep.wavelength*1000:.0f}",
                           f"{lib_rcwa.wavelength*1000:.0f}"),
        ("period (nm)",    f"{lib_meep.period*1000:.0f}",
                           f"{lib_rcwa.period*1000:.0f}"),
        ("height (nm)",    f"{lib_meep.pillar_height*1000:.0f}",
                           f"{lib_rcwa.pillar_height*1000:.0f}"),
        ("n_glass",        f"{lib_meep.n_glass:.2f}",
                           f"{lib_rcwa.n_glass:.2f}"),
        ("N (points)",     f"{len(lib_meep.widths)}",
                           f"{len(lib_rcwa.widths)}"),
        ("phase coverage", f"{lib_meep.phase_coverage():.1f}°",
                           f"{lib_rcwa.phase_coverage():.1f}°"),
    ]

    col_w = [20, 20, 20]
    sep   = "─" * (col_w[0] + col_w[1] + col_w[2] + 6)
    hdr   = (f"{'Parameter':<{col_w[0]}}  "
             f"{'MEEP FDTD':^{col_w[1]}}  "
             f"{'torcwa RCWA':^{col_w[2]}}")

    print(f"\n[compare] ── Library Metadata {'─'*30}")
    print(hdr)
    print(sep)
    for label, vm, vr in rows:
        print(f"{label:<{col_w[0]}}  {vm:^{col_w[1]}}  {vr:^{col_w[2]}}")
    print(sep)

    if rcwa_time_s is not None:
        print(f"\n  RCWA sweep time  : {rcwa_time_s:.1f} s  "
              f"({rcwa_time_s/len(lib_rcwa.widths):.2f} s/point)")


def print_speed_table(meep_time_s, rcwa_time_s, n_widths):
    """Print speed comparison table when both timings are available."""
    if meep_time_s is None or rcwa_time_s is None:
        if rcwa_time_s is not None:
            print(f"\n[compare] RCWA total: {rcwa_time_s:.1f} s  "
                  f"({rcwa_time_s/n_widths:.2f} s/point)")
            print(f"[compare] Pass --meep-time <seconds> to see speedup.")
        return

    speedup   = meep_time_s / rcwa_time_s
    ppm       = meep_time_s / n_widths
    rpm       = rcwa_time_s / n_widths

    w = [14, 10, 16, 14]
    line = "─" * (sum(w) + len(w) * 2 + 1)
    def row(a, b, c, d):
        return f"  {a:<{w[0]}}  {b:>{w[1]}}  {c:>{w[2]}}  {d:>{w[3]}}"

    print(f"\n[compare] ── Speed Comparison {'─'*32}")
    print(row("Solver", "N points", "Total time (s)", "Time/point (s)"))
    print("  " + line)
    print(row("MEEP FDTD",   n_widths, f"{meep_time_s:.1f}", f"{ppm:.2f}"))
    print(row("torcwa RCWA", n_widths, f"{rcwa_time_s:.1f}", f"{rpm:.4f}"))
    print("  " + line)
    print(row("Speedup", "—", f"{speedup:.1f}×", f"{speedup:.1f}×"))
    print()


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    args   = parse_args()
    outdir = os.path.join(_HERE, args.outdir)
    os.makedirs(outdir, exist_ok=True)

    print_platform_info()

    # Load libraries
    print(f"\n[compare] Loading MEEP library : {args.meep_lib}")
    lib_meep = PhaseLibrary.load(args.meep_lib)

    print(f"[compare] Loading RCWA library : {args.rcwa_lib}")
    lib_rcwa = PhaseLibrary.load(args.rcwa_lib)

    rcwa_time_s = _load_rcwa_time(args.rcwa_lib)

    # Print tables
    print_metadata_table(lib_meep, lib_rcwa, rcwa_time_s)
    print_speed_table(args.meep_time, rcwa_time_s, len(lib_rcwa.widths))

    # Phase alignment (optional)
    phases_meep = lib_meep.phases_unwrapped
    phases_rcwa = lib_rcwa.phases_unwrapped

    if args.align_phase:
        # Interpolate RCWA phase at the first MEEP width to find offset
        offset = np.interp(lib_meep.widths[0], lib_rcwa.widths, phases_rcwa) \
                 - phases_meep[0]
        phases_rcwa = phases_rcwa - offset
        print(f"[compare] Phase alignment: shifted RCWA by {np.degrees(offset):+.1f}°")

    # Comparison plot
    if not args.no_plot:
        plot_path = os.path.join(outdir, "solver_comparison.png")
        plot_solver_comparison(
            widths_meep    = lib_meep.widths,
            amplitudes_meep= lib_meep.amplitudes,
            phases_meep    = phases_meep,
            widths_rcwa    = lib_rcwa.widths,
            amplitudes_rcwa= lib_rcwa.amplitudes,
            phases_rcwa    = phases_rcwa,
            period         = lib_meep.period,
            wavelength     = lib_meep.wavelength,
            filename       = plot_path,
        )

    print("\n[compare] Done.")


if __name__ == "__main__":
    main()
